### PR TITLE
Fixing bad interaction between cider-0.9.0-SNAPSHOT and lein-ancient

### PR DESCRIPTION
**Pull request by bcotton**

### CODE REVIEW

**Comment by jakepearson** [comment]
:shipit: :ship: :fried_shrimp:

**Comment by osulehria** [comment]
+1 to merging this, this dependency upgrade fixes issues with using leiningen.

**Comment by bcotton** [comment]
ping

**Comment by grammati** [comment]
Someone else already pushed the same change.

**Pull request closed without merging**
